Source/GalaxyStorm/Web/GalaxyStorm.Web/Areas/Admiral/Controllers/ShardsController.cs
namespace GalaxyStorm.Web.Areas.Admiral.Controllers
{
    using System.Web.Mvc;
    using AutoMapper;
    using AutoMapper.QueryableExtensions;
    using Data.Models;
    using Kendo.Mvc.Extensions;
    using Kendo.Mvc.UI;
    using Services.Data.Contracts;
    using ViewModels.Common;
    using ViewModels.Shards;

    public class ShardsController : Controller
    {
        private readonly IPlanetService planetService;
        private readonly IShardService shardService;

        public ShardsController(IPlanetService planetService, IShardService shardService)
        {
            this.planetService = planetService;
            this.shardService = shardService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Read([DataSourceRequest]DataSourceRequest request)
        {
            var shards = this.shardService.GetShards().ProjectTo<SimpleShardViewModel>();
            
            DataSourceResult result = shards.ToDataSourceResult(request);

            return Json(result);
        }

        public ActionResult ReadPlanets([DataSourceRequest] DataSourceRequest request, int shardId)
        {
            var planets = this.planetService.GetPlanetsByShardId(shardId).ProjectTo<PlayerPlanetViewModel>();

            var result = planets.ToDataSourceResult(request);

            return Json(result);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Update([DataSourceRequest]DataSourceRequest request, SimpleShardViewModel shard)
        {
            if (ModelState.IsValid)
            {
                var mappedShard = Mapper.Map<Shard>(shard);

                this.shardService.UpdateShard(mappedShard);
            }

            return Json(new[] { shard }.ToDataSourceResult(request, ModelState));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return null;
        }

        [HttpPost]
        public ActionResult Create(Shard shard)
        {
            return null;
        }
    }
}

Source/GalaxyStorm/Web/GalaxyStorm.Web/Areas/Planet/Controllers/FleetController.cs
namespace GalaxyStorm.Web.Areas.Planet.Controllers
{
    using System.Web.Mvc;
    using Hangfire;
    using Infrastructure;
    using Logic.Core;
    using Microsoft.AspNet.Identity;
    using Services.Data;
    using Services.Data.Contracts;
    using Services.Web.Contracts;
    using ViewModels.Fleet;

    public class FleetController : UsersController
    {
        private readonly IBuildingsService buildingsService;
        private readonly IFleetService fleetService;
        private readonly IPlayerService playerService;
        private readonly ITechnologiesService techService;
        private readonly ILogicProvider logic;
        private readonly IBackgroundWorkerService<IFleetService> worker;

        public FleetController(IPlayerService playerService, IBuildingsService buildingsService, IFleetService fleetService, ITechnologiesService techService, ILogicProvider logic, IBackgroundWorkerService<IFleetService> worker)
        {
            this.playerService = playerService;
            this.buildingsService = buildingsService;
            this.fleetService = fleetService;
            this.techService = techService;
            this.logic = logic;
            this.worker = worker;
        }

        // GET: Planet/Fleet
        public ActionResult Index()
        {
            var userId = User != null ? User.Identity.GetUserId() : string.Empty;

            var barracksLevel = this.buildingsService.GetPlayerBuildings(userId).BarracksLevel;
            var fleet = this.fleetService.GetPlayerFleet(userId);
            var cheaperFleet = this.techService.GetPlayerTechnologies(userId).CheaperFleetLevel;

            var cheaperFleetModifier = this.logic.Technologies.CheaperFleet.Modifier[cheaperFleet];

            var vM = new FleetViewModel(barracksLevel, fleet)
            {
                Scout = new UnitViewModel(fleet.ScoutsQuantity, fleet.DispatchedScouts, this.logic.Ships.Scout, cheaperFleetModifier),
                Carrier = new UnitViewModel(fleet.CarriersQuantity, fleet.DispatchedCarriers, this.logic.Ships.Carrier, cheaperFleetModifier),
                Fighter = new UnitViewModel(fleet.FighterQuantity, fleet.DispatchedFighters, this.logic.Ships.Fighter, cheaperFleetModifier),
                Interceptor = new UnitViewModel(fleet.InterceptorQuantity, fleet.DispatchedInterceptors, this.logic.Ships.Interceptor, cheaperFleetModifier),
                Bomber = new UnitViewModel(fleet.BomberQuantity, fleet.DispatchedBombers, this.logic.Ships.Bomber, cheaperFleetModifier),
                Juggernaut = new UnitViewModel(fleet.JuggernautQuantity, fleet.DispatchedJuggernauts, this.logic.Ships.Juggernaut, cheaperFleetModifier)
            };

            var reqRes = this.playerService.GetPlayerResources(userId);
            ViewBag.Energy = reqRes.Energy;
            ViewBag.Crystal = reqRes.Crystal;
            ViewBag.Metal = reqRes.Metal;

            return View(vM);
        }

        public ActionResult Scout()
        {
            var userId = User != null ? User.Identity.GetUserId() : string.Empty;

            var modifier = this.GetCheaperFleetModifier(userId);

            var vM = new UnitViewModel(this.logic.Ships.Scout, modifier);

            return View(vM);
        }

        public ActionResult Carrier()
        {
            var userId = User != null ? User.Identity.GetUserId() : string.Empty;

            var modifier = this.GetCheaperFleetModifier(userId);

            var vM = new UnitViewModel(this.logic.Ships.Carrier, modifier);

            return View(vM);
        }

        public ActionResult Fighter()
        {
            var userId = User != null ? User.Identity.GetUserId() : string.Empty;

            var modifier = this.GetCheaperFleetModifier(userId);

            var vM = new UnitViewModel(this.logic.Ships.Fighter, modifier);

            return View(vM);
        }

        public ActionResult Bomber()
        {
            var userId = User != null ? User.Identity.GetUserId() : string.Empty;

            var modifier = this.GetCheaperFleetModifier(userId);

            var vM = new UnitViewModel(this.logic.Ships.Bomber, modifier);

            return View(vM);
        }

        public ActionResult Interceptor()
        {
            var userId = User != null ? User.Identity.GetUserId() : string.Empty;

            var modifier = this.GetCheaperFleetModifier(userId);

            var vM = new UnitViewModel(this.logic.Ships.Interceptor, modifier);

            return View(vM);
        }

        public ActionResult Juggernaut()
        {
            var userId = User != null ? User.Identity.GetUserId() : string.Empty;

            var modifier = this.GetCheaperFleetModifier(userId);

            var vM = new UnitViewModel(this.logic.Ships.Juggernaut, modifier);

            return View(vM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RecruitScouts(int amount)
        {
            var userId = User != null ? User.Identity.GetUserId() : "";

            var timespan = this.fleetService.ScheduleRecruitScout(userId, amount);

            if (timespan != null)
            {
                this.worker.Schedule(x => x.CompleteRecruiting(userId), timespan.Value);
            }
            else
            {
                this.SetErrorMessage();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RecruitFighters(int amount)
        {
            var userId = User != null ? User.Identity.GetUserId() : string.Empty;

            var timespan = this.fleetService.ScheduleRecruitFighter(userId, amount);

            if (timespan != null)
            {
                this.worker.Schedule(x => x.CompleteRecruiting(userId), timespan.Value);
            }
            else
            {
                this.SetErrorMessage();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RecruitCarriers(int amount)
        {
            var userId = User != null ? User.Identity.GetUserId() : string.Empty;

            var timespan = this.fleetService.ScheduleRecruitCarrier(userId, amount);

            if (timespan != null)
            {
                this.worker.Schedule(x => x.CompleteRecruiting(userId), timespan.Value);
            }
            else
            {
                this.SetErrorMessage();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RecruitBombers(int amount)
        {
            var userId = User != null ? User.Identity.GetUserId() : string.Empty;

            var timespan = this.fleetService.ScheduleRecruitBomber(userId, amount);

            if (timespan != null)
            {
                this.worker.Schedule(x => x.CompleteRecruiting(userId), timespan.Value);
            }
            else
            {
                this.SetErrorMessage();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RecruitInterceptors(int amount)
        {
            var userId = User != null ? User.Identity.GetUserId() : string.Empty;

            var timespan = this.fleetService.ScheduleRecruitInterceptor(userId, amount);

            if (timespan != null)
            {
                this.worker.Schedule(x => x.CompleteRecruiting(userId), timespan.Value);
            }
            else
            {
                this.SetErrorMessage();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RecruitJuggernauts(int amount)
        {
            var userId = User != null ? User.Identity.GetUserId() : string.Empty;

            var timespan = this.fleetService.ScheduleRecruitJuggernaut(userId, amount);

            if (timespan != null)
            {
                this.worker.Schedule(x => x.CompleteRecruiting(userId), timespan.Value);
            }
            else
            {
                this.SetErrorMessage();
            }

            return RedirectToAction("Index");
        }

        protected override void SetErrorMessage()
        {
            TempData["Error"] =
                "You cannot recruit that many ships at the moment. You don't meet the requirements, or another batch of ships is being recruited!";
        }

        private double GetCheaperFleetModifier(string userId)
        {
            var cheaperFleet = this.techService.GetPlayerTechnologies(userId).CheaperFleetLevel;
            var cheaperFleetModifier = this.logic.Technologies.CheaperFleet.Modifier[cheaperFleet];

            return cheaperFleetModifier;
        }
    }
}

Source/GalaxyStorm/Web/GalaxyStorm.Web/Areas/Public/Controllers/InfoController.cs
namespace GalaxyStorm.Web.Areas.Public.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using AutoMapper.QueryableExtensions;
    using Infrastructure;
    using Services.Data.Contracts;
    using ViewModels.Info;

    public class InfoController : BaseController
    {
        private readonly IInfoService infoService;

        public InfoController(IInfoService infoService)
        {
            this.infoService = infoService;
        }

        // GET: Public/Info
        public ActionResult Index()
        {
            var topTen = this.Cache.Get("topLb", () => this.infoService
                .GetTopPlayersInShards(10)
                .ProjectTo<InfoLeaderboardsViewModel>()
                .ToList(), 60 * 30);

            return View(topTen);
        }

        public ActionResult TopPlanet()
        {
            var topFiveCombat = this.Cache.Get("topPlanetLb", () => this.infoService
                .GetTopPlayerWithPlanetPoints(5)
                .ProjectTo<InfoLeaderboardsViewModel>()
                .ToList(), 60 * 30);

            return PartialView(topFiveCombat);
        }

        public ActionResult TopNeutral()
        {
            var topFiveCombat = this.Cache.Get("topNeutralLb", () => this.infoService
                .GetTopPlayersWithNeutralPoints(5)
                .ProjectTo<InfoLeaderboardsViewModel>()
                .ToList(), 60 * 30);

            return PartialView(topFiveCombat);
        }

        public ActionResult TopCombat()
        {
            var topFiveCombat = this.Cache.Get("topCombatLb", () => this.infoService
                .GetTopPlayersWithCombatPoints(5)
                .ProjectTo<InfoLeaderboardsViewModel>()
                .ToList(), 60 * 30);

            return PartialView(topFiveCombat);
        }
    }
}

Source/GalaxyStorm/Web/GalaxyStorm.Web/Areas/Shard/Controllers/PreviewController.cs
namespace GalaxyStorm.Web.Areas.Shard.Controllers
{
    using System.Web.Mvc;
    using AutoMapper;
    using Infrastructure;
    using Microsoft.AspNet.Identity;
    using Services.Data.Contracts;
    using ViewModels.Common;

    public class PreviewController : UsersController
    {
        private readonly IShardService shardService;
        private readonly IPlanetService planetService;

        public PreviewController(IShardService shardService, IPlanetService planetService)
        {
            this.shardService = shardService;
            this.planetService = planetService;
        }

        // GET: Shard/Preview
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();

            var currentShard = this.shardService.GetShardByPlayerId(userId);

            var currentPlayerPlanet = planetService.GetPlayerPlanet(userId);

            ViewData["PlayerPlanet"] = currentPlayerPlanet.Title;

            var vM = Mapper.Map<PublicShardViewModel>(currentShard);

            return View(vM);
        }
    }
}

Source/GalaxyStorm/Web/GalaxyStorm.Web/Views/Shared/_FleetPartial.cshtml
@model GalaxyStorm.ViewModels.Fleet.FleetViewModel

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h6 class="text-center">
                    @Html.ActionLink(@Model.Scout.Name, "Scout", "Fleet", new { area = "Planet" }, null)
                </h6>
            </div>
            <div class="panel-body text-center">
                <img src="~/Images/100xX/scout.png" alt="scout" class="small-img-100" />
                <hr />
                <h4 class="text-center">
                    @Model.Scout.AmountOnPlanet / @(Model.Scout.AmountOnPlanet + Model.Scout.AmountDispatched)
                </h4>
                @Html.ActionLink("Recruit", "Index", "Fleet", new { area = "Planet" }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h6 class="text-center">
                    @Html.ActionLink(@Model.Carrier.Name, "Carrier", "Fleet", new { area = "Planet" }, null)
                </h6>
            </div>
            <div class="panel-body text-center">
                <img src="~/Images/100xX/carrier.png" alt="carrier" class="small-img-100" />
                <hr />
                <h4 class="text-center">
                    @Model.Carrier.AmountOnPlanet / @(Model.Carrier.AmountOnPlanet + Model.Carrier.AmountDispatched)
                </h4>
                @Html.ActionLink("Recruit", "Index", "Fleet", new { area = "Planet" }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h6 class="text-center">
                    @Html.ActionLink(@Model.Fighter.Name, "Fighter", "Fleet", new { area = "Planet" }, null)
                </h6>
            </div>
            <div class="panel-body text-center">
                <img src="~/Images/100xX/fighter.png" alt="fighter" class="small-img-100" />
                <hr />
                <h4 class="text-center">
                    @Model.Fighter.AmountOnPlanet / @(Model.Fighter.AmountOnPlanet + Model.Fighter.AmountDispatched)
                </h4>
                @Html.ActionLink("Recruit", "Index", "Fleet", new { area = "Planet" }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h6 class="text-center">
                    @Html.ActionLink(@Model.Interceptor.Name, "Interceptor", "Fleet", new { area = "Planet" }, null)
                </h6>
            </div>
            <div class="panel-body text-center">
                <img src="~/Images/100xX/interceptor.png" alt="interceptor" class="small-img-100" />
                <hr />
                <h4 class="text-center">
                    @Model.Interceptor.AmountOnPlanet / @(Model.Interceptor.AmountOnPlanet + Model.Interceptor.AmountDispatched)
                </h4>
                @Html.ActionLink("Recruit", "Index", "Fleet", new { area = "Planet" }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h6 class="text-center">
                    @Html.ActionLink(@Model.Bomber.Name, "Bomber", "Fleet", new { area = "Planet" }, null)
                </h6>
            </div>
            <div class="panel-body text-center">
                <img src="~/Images/100xX/bomber.png" alt="bomber" class="small-img-100" />
                <hr />
                <h4 class="text-center">
                    @Model.Bomber.AmountOnPlanet / @(Model.Bomber.AmountOnPlanet + Model.Bomber.AmountDispatched)
                </h4>
                @Html.ActionLink("Recruit", "Index", "Fleet", new { area = "Planet" }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h6 class="text-center">
                    @Html.ActionLink(@Model.Juggernaut.Name, "Juggernaut", "Fleet", new { area = "Planet" }, null)
                </h6>
            </div>
            <div class="panel-body text-center">
                <img src="~/Images/100xX/juggernaut.png" alt="juggernaut" class="small-img-100" />
                <hr />
                <h4 class="text-center">
                    @Model.Juggernaut.AmountOnPlanet / @(Model.Juggernaut.AmountOnPlanet + Model.Juggernaut.AmountDispatched)
                </h4>
                @Html.ActionLink("Recruit", "Index", "Fleet", new { area = "Planet" }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>

Source/GalaxyStorm/Web/GalaxyStorm.Web/Views/Shared/_NavbarPartial.cshtml
<div class="navbar navbar-inverse navbar-fixed-top" id="navbar">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Galaxy Storm", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @if (Request.IsAuthenticated)
                {
                    <li class="dropdown">
                        <a href="/#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="ion-planet size-18"> </i> Planet <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Preview", new { area = "Planet"})"><i class="ion-ios-world size-18"> </i> Preview</a></li>
                            <li><a href="@Url.Action("Index", "Buildings", new { area = "Planet"})"><i class="ion-hammer size-18"> </i> Build</a></li>
                            <li><a href="@Url.Action("Index", "Technologies", new { area = "Planet"})"><i class="ion-ios-flask size-18"> </i> Research</a></li>
                            <li><a href="@Url.Action("Index", "Fleet", new { area = "Planet"})"><i class="ion-jet size-18"> </i> Recruit</a></li>
                        </ul>
                    </li>
                    <li><a href="@Url.Action("Index", "Fleet", new { area = "Planet"})"><i class="ion-jet size-18"> </i> Fleet</a></li>
                    <li><a href="@Url.Action("Index", "Preview", new { area = "Shard"})"><i class="ion-ios-ionic-outline size-18"> </i> Shard</a></li>
                }

                @if (Request.IsAuthenticated && User.IsInRole("Admiral"))
                {
                    <li><a href="/Admiral/Home"><i class="ion-settings size-18"> </i> Admiral</a></li>
                }

                <li><a href="@Url.Action("Index", "Info", new {area= "Public"})"><i class="ion-information size-18"> </i></a></li>
            </ul>

            @Html.Partial("_LoginPartial")
        </div>
    </div>
    @Html.Partial("_ResourceHUDPartial")
</div>

Source/GalaxyStorm/Web/GalaxyStorm.Web/Views/Shared/_PrivateLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
    <title>@ViewBag.Title - Galaxy Storm - the Game</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/public")
    @Styles.Render("~/Content/jqueryui")
    @Styles.Render("~/Content/hex")

    @RenderSection("styles", required: false)

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("headscripts", required: false)
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    @Html.Partial("_NavbarPartial")

    <!-- loader -->
    <div id="site-loader">
        <div class="loader"></div>
    </div>
    <!-- loader -->

    <div id="site-wrap">

        <div id="bg">
            <div id="img"></div>
            <div id="overlay"></div>
        </div>

        <div class="container body-content">
            <div class="row">
                @{ Html.RenderPartial("_SideMenuPartial");}
                <div class="col-md-9">
                    <div>
                        @if (TempData["Error"] != null)
                        {
                            <div class="panel panel-danger">
                                <div class="panel-heading text-center">@TempData["Error"]</div>
                            </div>
                        }
                        @if (TempData["Info"] != null)
                        {
                            <div class="panel panel-info">
                                <div class="panel-heading panel-info">@TempData["Info"]</div>
                            </div>
                        }
                        @if (TempData["Success"] != null)
                        {
                            <div class="panel panel-success">
                                <div class="panel-heading text-center">@TempData["Success"]</div>
                            </div>
                        }
                    </div>

                    @RenderBody()
                </div>
            </div>

            <footer>
                <hr />
                <p class="text-center">Peter Kanev &copy; @DateTime.Now.Year - Galaxy Storm - the Game</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/common")
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</body>
</html>

Source/GalaxyStorm/Web/GalaxyStorm.Web/Views/Shared/_PublicLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
    <title>@ViewBag.Title - Galaxy Storm - the Game</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/public")
</head>
<body>
    @Html.Partial("_NavbarPartial")

    <!-- loader -->
    <div id="site-loader">
        <div class="loader"></div>
    </div>
    <!-- loader -->

    <div id="site-wrap">

        <div id="bg">
            <div id="img"></div>
            <div id="overlay"></div>
            <canvas id="js-canvas"></canvas>
        </div>

        <div class="container body-content">
            @RenderBody()

            <footer>
                <hr />
                <p class="text-center">Peter Kanev &copy; @DateTime.Now.Year - Galaxy Storm - the Game</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/public")
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</body>
</html>

Source/GalaxyStorm/Web/GalaxyStorm.Web/Views/Shared/_ResourceHUDPartial.cshtml
@if(User.Identity.IsAuthenticated){

    <div class="hud">
        <div class="resources">
            <div class="border-left-sharp"></div>
            @{
                Html.RenderAction("Resources", "Preview", new {Area = "Planet"});
            }
            <div class="border-right-sharp"></div>
        </div>
    </div>

}

Source/GalaxyStorm/Web/GalaxyStorm.Web/Views/Shared/_SideMenuPartial.cshtml
<div class="col-md-3 nav-side-menu">
    <div class="brand">Galaxy Storm (logo)</div>
    <i class="ion-navicon toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>

    <div class="menu-list">

        <ul id="menu-content" class="menu-content collapse out">
            <li class="active">
                <a href="@Url.Action("Index", "Preview", new {area = "Planet"})">
                    <i class="ion-ios-world size-18"></i> Overview
                </a>
            </li>

            <li data-toggle="collapse" data-target="#buildings" class="collapsed">
                <a href="#"><i class="ion-hammer size-18"> </i> Build <span class="arrow"></span></a>
            </li>
            <ul class="sub-menu collapse" id="buildings">
                <li class="active"><a href="@Url.Action("Index", "Buildings", new {area = "Planet"})"> Overview</a></li>
                <li><a href="@Url.Action("Headquarters", "Buildings", new {area = "Planet"})"><i class="ion-home size-18"> </i> Headquarters</a></li>
                <li><a href="@Url.Action("SolarCollector", "Buildings", new {area = "Planet"})"><i class="ion-ios-sunny-outline size-18"> </i> Solar Collector</a></li>
                <li><a href="@Url.Action("CrystalExtractor", "Buildings", new {area = "Planet"})"><i class="ion-ios-flower-outline size-18"> </i> Crystal Extractor</a></li>
                <li><a href="@Url.Action("MetalScrapper", "Buildings", new {area = "Planet"})"><i class="ion-ios-cog-outline size-18"> </i> Metal Scrapper</a></li>
                <li><a href="@Url.Action("ResearchCentre", "Buildings", new {area = "Planet"})"><i class="ion-ios-flask size-18"> </i> Research Centre</a></li>
                <li><a href="@Url.Action("Barracks", "Buildings", new {area = "Planet"})"><i class="ion-jet size-18"> </i> Barracks</a></li>
            </ul>

            <li data-toggle="collapse" data-target="#research" class="collapsed">
                <a href="#"><i class="ion-ios-flask size-18"> </i> Research <span class="arrow"></span></a>
            </li>
            <ul class="sub-menu collapse" id="research">
                <li class="active"><a href="@Url.Action("Index", "Technologies", new {area = "Planet"})">Overview</a></li>
            </ul>

            <li data-toggle="collapse" data-target="#new" class="collapsed">
                <a href="#"><i class="ion-jet size-18"></i> Recruit <span class="arrow"></span></a>
            </li>
            <ul class="sub-menu collapse" id="new">
                <li class="active"><a href="@Url.Action("Index", "Fleet", new {area = "Planet"})">Overview</a></li>
                <li><a href="#"><i class="ion-jet size-18"> </i> Dispatched Units</a></li>
                <li><a href="#"><i class="ion-ios-world size-18"> </i> Stationed Units</a></li>
            </ul>

            <li>
                <a href="@Url.Action("Index", "Preview", new {area = "Profile"})">
                    <i class="ion-wrench size-18"> </i> Profile
                </a>
            </li>

            @if (User.IsInRole("Admiral"))
            {
                <li data-toggle="collapse" data-target="#admiral" class="collapsed">
                    <a href="#"><i class="ion-settings size-18"> </i> Admiral's Quarters <span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="admiral">
                    <li><a href="#"><i class="ion-settings size-18"> </i> Quarters</a></li>
                    <li><a href="#"><i class="ion-ios-people size-18"> </i> Manage Users</a></li>
                    <li><a href="@Url.Action("Index", "Shards", new { area = "Admiral"})"><i class="ion-ionic size-18"> </i> Manage Shards</a></li>
                    <li><a href="@Url.Action("Index", "Broadcast", new { area = "Admiral"})"><i class="ion-speakerphone size-18"> </i> Broadcast</a></li>
                    <li><a href="@Url.Action("Index", "Supplements", new { area = "Admiral"})"><i class="ion-paper-airplane size-18"> </i> Send Supplements</a></li>
                </ul>
            }
        </ul>
    </div>
</div>