Source/GalaxyStorm/Web/GalaxyStorm.Web/Areas/Planet/Controllers/PreviewController.cs
namespace GalaxyStorm.Web.Areas.Planet.Controllers
{
    using System.Web.Mvc;
    using AutoMapper;
    using Infrastructure;
    using Logic.Core;
    using Microsoft.AspNet.Identity;
    using Services.Data.Contracts;
    using ViewModels.Buildings;
    using ViewModels.Common;
    using Data.Models;
    using ViewModels.Fleet;
    using ViewModels.Technologies;

    public class PreviewController : UsersController
    {
        private readonly IPlayerService playerService;
        private readonly ILogicProvider logic;

        public PreviewController(IPlayerService playerService, ILogicProvider logic)
        {
            this.playerService = playerService;
            this.logic = logic;
        }

        // GET: Planet/Index
        public ActionResult Index()
        {
            var userId = User != null ? User.Identity.GetUserId() : string.Empty;

            var pO = this.playerService.GetPlayerInformation(userId);
            var hourlyRes = this.playerService.GetHourlyResourceIncome(userId);

            var info = new CompletePlayerViewModel
            {
                Resources = new ResourcesViewModel
                {
                    Energy = pO.Resources.Energy,
                    Crystal = pO.Resources.Crystal,
                    Metal = pO.Resources.Metal,
                    EnergyPerHour = hourlyRes[0],
                    CrystalPerHour = hourlyRes[1],
                    MetalPerHour = hourlyRes[2]
                },
                Buildings = new BuildingsViewModel(pO.Buildings)
                {
                    Headquarters = new BuildingViewModel(pO.Buildings.HeadQuartersLevel, this.logic.Buildings.Headquarters),
                    ResearchCentre = new BuildingViewModel(pO.Buildings.ResearchCentreLevel, this.logic.Buildings.ResearchCentre),
                    Barracks = new BuildingViewModel(pO.Buildings.BarracksLevel, this.logic.Buildings.Barracks),
                    SolarCollector = new ResourceBuildingViewModel(pO.Buildings.SolarCollectorLevel, this.logic.Buildings.SolarCollector),
                    CrystalExtractor = new ResourceBuildingViewModel(pO.Buildings.CrystalExtractorLevel, this.logic.Buildings.CrystalExtractor),
                    MetalScrapper = new ResourceBuildingViewModel(pO.Buildings.MetalScrapperLevel, this.logic.Buildings.MetalScrapper),
                },
                Technologies = new TechnologiesViewModel(pO.Buildings.ResearchCentreLevel, pO.Technologies)
                {
                    FasterConstruction = new TechnologyViewModel(pO.Technologies.FasterConstructionLevel, this.logic.Technologies.FasterConstruction),
                    MoreResources = new TechnologyViewModel(pO.Technologies.MoreResourcesLevel, this.logic.Technologies.MoreResources),
                    ArmoredFleet = new TechnologyViewModel(pO.Technologies.ArmoredFleetLevel, this.logic.Technologies.ArmoredFleet),
                    CheaperFleet = new TechnologyViewModel(pO.Technologies.CheaperFleetLevel, this.logic.Technologies.CheaperFleet),
                    LargerFleet = new TechnologyViewModel(pO.Technologies.LargerFleetLevel, this.logic.Technologies.LargerFleet)
                },
                Fleet = new FleetViewModel
                {
                    Scout = new UnitViewModel(pO.Units.ScoutsQuantity, pO.Units.DispatchedScouts, this.logic.Ships.Scout.Name),
                    Carrier = new UnitViewModel(pO.Units.CarriersQuantity, pO.Units.DispatchedCarriers, this.logic.Ships.Carrier.Name),
                    Fighter = new UnitViewModel(pO.Units.FighterQuantity, pO.Units.DispatchedFighters, this.logic.Ships.Fighter.Name),
                    Interceptor = new UnitViewModel(pO.Units.InterceptorQuantity, pO.Units.DispatchedInterceptors, this.logic.Ships.Interceptor.Name),
                    Bomber = new UnitViewModel(pO.Units.BomberQuantity, pO.Units.DispatchedBombers, this.logic.Ships.Bomber.Name),
                    Juggernaut = new UnitViewModel(pO.Units.JuggernautQuantity, pO.Units.DispatchedJuggernauts, this.logic.Ships.Juggernaut.Name)
                }
            };

            // Automapper mapping
            info.Planet = Mapper.Map<Planet, PlanetViewModel>(pO.Planet);

            return View(info);
        }
        
        [ChildActionOnly]
        public ActionResult Resources()
        {
            var userId = User != null ? User.Identity.GetUserId() : string.Empty;

            var res = this.playerService.GetPlayerResources(userId);
            var hourlyRes = this.playerService.GetHourlyResourceIncome(userId);

            var resVM = new ResourcesViewModel
            {
                Energy = res.Energy,
                Crystal = res.Crystal,
                Metal = res.Metal,
                EnergyPerHour = hourlyRes[0],
                CrystalPerHour = hourlyRes[1],
                MetalPerHour = hourlyRes[2]
            };

            return View("_Resources", resVM);
        }
    }
}

Source/GalaxyStorm/Web/GalaxyStorm.Web/Areas/Profile/Controllers/PreviewController.cs
namespace GalaxyStorm.Web.Areas.Profile.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using AutoMapper;
    using Data.Models;
    using Data.Models.PlayerObjects;
    using Microsoft.AspNet.Identity;
    using Services.Data.Contracts;
    using ViewModels.Common;

    public class PreviewController : Controller
    {
        private readonly IReportsService reportsService;
        private readonly IPlayerService playerService;

        public PreviewController(IReportsService reportsService, IPlayerService playerService)
        {
            this.reportsService = reportsService;
            this.playerService = playerService;
        }

        // GET: Profile/Manage
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();

            var player = this.playerService.GetPlayerInformation(userId);

            var vM = Mapper.Map<PlayerObject, SimplePlayerViewModel>(player);

            return View(vM);
        }
    }
}

Source/GalaxyStorm/Web/GalaxyStorm.Web/Areas/Shard/Controllers/PlanetController.cs
namespace GalaxyStorm.Web.Areas.Shard.Controllers
{
    using System.Web.Mvc;
    using AutoMapper;
    using Data.Models;
    using Infrastructure;
    using Microsoft.AspNet.Identity;
    using Services.Data.Contracts;
    using ViewModels.Common;

    public class PlanetController : UsersController
    {
        private readonly IPlanetService planetService;

        public PlanetController(IPlanetService planetService)
        {
            this.planetService = planetService;
        }

        // GET: Shard/Planet
        public ActionResult Index(string shard, string planet)
        {
            var userId = User != null ? User.Identity.GetUserId() : "";

            var planetResult = planetService.GetPublicPlanet(userId, shard, planet);

            if (planetResult == null)
            {
                this.SetErrorMessage();
                return RedirectToAction("Index", "Preview", new { area = "Shard"});
            }

            var currentPlayerPlanet = planetService.GetPlayerPlanet(userId);

            ViewData["PlayerPlanet"] = currentPlayerPlanet.Title;

            var vM = Mapper.Map<Planet, PublicPlanetViewModel>(planetResult);

            return View(vM);
        }

        protected override void SetErrorMessage()
        {
            TempData["Error"] = "Could not find the planet you were looking for! Are you lost?";
        }
    }
}

Source/GalaxyStorm/Web/GalaxyStorm.Web/Areas/Shard/Controllers/PreviewController.cs
namespace GalaxyStorm.Web.Areas.Shard.Controllers
{
    using System.Web.Mvc;
    using AutoMapper;
    using Infrastructure;
    using Microsoft.AspNet.Identity;
    using Services.Data.Contracts;
    using ViewModels.Common;

    public class PreviewController : UsersController
    {
        private readonly IShardService shardService;
        private readonly IPlanetService planetService;

        public PreviewController(IShardService shardService, IPlanetService planetService)
        {
            this.shardService = shardService;
            this.planetService = planetService;
        }

        // GET: Shard/Preview
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();

            var currentShard = this.shardService.GetShardByPlayerId(userId);

            var currentPlayerPlanet = planetService.GetPlayerPlanet(userId);

            ViewData["PlayerPlanet"] = currentPlayerPlanet.Title;

            var vM = Mapper.Map<PublicShardViewModel>(currentShard);

            return View(vM);
        }
    }
}

Source/GalaxyStorm/Web/GalaxyStorm.Web/Areas/Profile/Views/Preview/Index.cshtml
@model GalaxyStorm.ViewModels.Common.SimplePlayerViewModel

@{
    ViewBag.Title = "Profile";
}

<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">
            Player Information
        </h2>
    </div>
</div>

<div class="well">
    <div class="row text-center">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>@Model.DisplayName</h3>
            </div>
        </div>
        @if (Model.NumberOfReports > 0)
        {
            <div class="panel panel-success">
                <div class="panel-heading">
                    <span><a href="#"><i class="ion-ios-bell size-18"> </i> You have <span class="badge">@Model.NumberOfReports</span> new reports!</a></span>
                </div>
            </div>
        }
        else
        {
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span><i class="ion-ios-bell-outline size-18"> </i> You have no new reports.</span>
                </div>
            </div>
        }
    </div>
    <div class="row text-center">
        <div class="col-md-6">
            <h4>Points</h4>
            <hr />
            <div class="row">
                <div class="col-md-4">
                    <span data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Gained by upgrading buildings and researching new technologies.">
                        <i class="ion-planet size-18"> </i>  @Model.PlanetPoints Planet
                    </span>
                </div>
                <div class="col-md-4">
                    <span data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Gained by recruiting new units.">
                        <i class="ion-jet size-18"> </i> @Model.NeutralPoints Neutral
                    </span>
                </div>
                <div class="col-md-4">
                    <span data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Gained by participating in battles.">
                        <i class="ion-nuclear size-18"> </i> @Model.CombatPoints Combat
                    </span>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <h4>Your Planet</h4>
            <hr />
            <p>
                <a href="@Url.Action("Index", "Planet", new { area = "Shard" })/@Model.Planet.ShardTitle/@Model.Planet.Title">@Model.Planet.Title (@Model.Planet.X : @Model.Planet.Y) - @Model.Planet.ShardTitle</a>
            </p>
            <p>Modifiers</p>
            <div class="row text-center">
                <div class="col-md-4 text-info"><span data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Energy income is modified by factor of @Model.Planet.EnergyModifier"><i class="ion-ios-sunny-outline size-18"> </i> @string.Format("{0:0.00}", Model.Planet.EnergyModifier)</span></div>
                <div class="col-md-4 text-danger"><span data-toggle="tooltip" data-placement="bottom" data-original-title="Crystal income is modified by factor of @Model.Planet.CrystalModifier"><i class="ion-ios-flower-outline size-18"> </i> @string.Format("{0:0.00}", Model.Planet.CrystalModifier)</span></div>
                <div class="col-md-4 text-primary"><span data-toggle="tooltip" data-placement="bottom" data-original-title="Metal income is modified by factor of @Model.Planet.MetalModifier"><i class="ion-ios-cog-outline size-18"> </i> @string.Format("{0:0.00}", Model.Planet.MetalModifier)</span></div>
            </div>
            <br />
        </div>
    </div>
    <div class="row text-center">
        @Html.ActionLink("Change password", "ChangePassword", "Manage", null, new { @class = "btn btn-block btn-default" })
        <a href="#" class="btn btn-block btn-danger"><i class="ion-key size-18"> </i> Lock account</a>
    </div>
</div>